spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenexpiration: 7200 # 2h
    refresTokenexpiration: 604800 # 7 days
  profiles:
    active: dev
stripe:
  webhookSecretKey = ${STRIPE_WEBHOOK_SECRET_KEY}
  secretKey= ${STRIPE_SECRET_KEY}
